In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('noahs-csv/noahs-customers.csv')

In [36]:
df.shape

(11080, 6)

In [37]:
df.head()

,customerid,name,address,citystatezip,birthdate,phone
0,1001,Jack Quinn,201 E Park St,"Los Angeles, CA 91343",1960-05-14,805-287-8515
1,1002,David Powell,224C Tysens Ln,"Staten Island, NY 10306",1978-04-04,516-768-1652
2,1003,Carrie Green,1608 W 53rd Way,"Tampa, FL 33614",1969-01-21,727-209-0470
3,1004,Steven Miller,178½ E 7th St,"Manhattan, NY 10009",1953-08-17,607-941-9563
4,1005,Christine Powers,270 W 242nd St,"Bronx, NY 10463",1983-06-06,212-759-9043

In [39]:
number_dictionary = {
    'abc': 2,
    'def':3,
    'ghi':4,
    'jkl':5,
    'mno':6,
    'pqrs':7,
    'tuv':8,
    'wxyz':9
}

In [41]:
df['phone_clean'] = df.phone.str.replace('-', '')

In [46]:
df['last_name'] = df['name'].apply(lambda x: x.split()[-1].lower())

In [47]:
df['last_name'] = df['last_name'].str.split('')

In [48]:
df.head()

,customerid,name,address,citystatezip,birthdate,phone,phone_clean,last_name
0,1001,Jack Quinn,201 E Park St,"Los Angeles, CA 91343",1960-05-14,805-287-8515,8052878515,"[, q, u, i, n, n, ]"
1,1002,David Powell,224C Tysens Ln,"Staten Island, NY 10306",1978-04-04,516-768-1652,5167681652,"[, p, o, w, e, l, l, ]"
2,1003,Carrie Green,1608 W 53rd Way,"Tampa, FL 33614",1969-01-21,727-209-0470,7272090470,"[, g, r, e, e, n, ]"
3,1004,Steven Miller,178½ E 7th St,"Manhattan, NY 10009",1953-08-17,607-941-9563,6079419563,"[, m, i, l, l, e, r, ]"
4,1005,Christine Powers,270 W 242nd St,"Bronx, NY 10463",1983-06-06,212-759-9043,2127599043,"[, p, o, w, e, r, s, ]"

In [49]:
df.head(6)

,customerid,name,address,citystatezip,birthdate,phone,phone_clean,last_name
0,1001,Jack Quinn,201 E Park St,"Los Angeles, CA 91343",1960-05-14,805-287-8515,8052878515,"[, q, u, i, n, n, ]"
1,1002,David Powell,224C Tysens Ln,"Staten Island, NY 10306",1978-04-04,516-768-1652,5167681652,"[, p, o, w, e, l, l, ]"
2,1003,Carrie Green,1608 W 53rd Way,"Tampa, FL 33614",1969-01-21,727-209-0470,7272090470,"[, g, r, e, e, n, ]"
3,1004,Steven Miller,178½ E 7th St,"Manhattan, NY 10009",1953-08-17,607-941-9563,6079419563,"[, m, i, l, l, e, r, ]"
4,1005,Christine Powers,270 W 242nd St,"Bronx, NY 10463",1983-06-06,212-759-9043,2127599043,"[, p, o, w, e, r, s, ]"
5,1006,Amanda Ramirez,183-48 Camden Ave,"Saint Albans, NY 11412",1962-07-08,914-421-3167,9144213167,"[, r, a, m, i, r, e, z, ]"

In [61]:
number_list = []
for surname in df.last_name:
    name_values = []
    for char in surname:
        for key in number_dictionary:
            if char == '':
                pass
            elif char in key:
                name_values.append(number_dictionary[key])
                
    number_list.append(name_values)

In [62]:
number_list

[[7, 8, 4, 6, 6],
 [7, 6, 9, 3, 5, 5],
 [4, 7, 3, 3, 6],
 [6, 4, 5, 5, 3, 7],
 [7, 6, 9, 3, 7, 7],
 [7, 2, 6, 4, 7, 3, 9],
 [2, 6, 5, 5, 4, 6, 7],
 [7, 8, 3, 8, 3, 6, 7],
 [3, 6, 9, 5, 3, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [2, 7, 6, 9, 6],
 [9, 2, 5, 5, 3, 7],
 [2, 6, 6, 5],
 [7, 4, 6, 7],
 [2, 2, 6, 7, 2, 3, 5, 5],
 [6, 6, 6, 7, 3],
 [7, 6, 4, 8, 4],
 [7, 8, 3, 8, 3, 6, 7],
 [6, 6, 7, 7, 4, 7],
 [7, 2, 7, 5, 7],
 [9, 7, 4, 4, 4, 8],
 [2, 4, 2, 8, 3, 9],
 [9, 2, 8, 5, 4, 6, 7],
 [4, 2, 5, 8, 2, 6],
 [2, 4, 2, 8, 3, 9],
 [4, 4, 2, 7, 6, 6],
 [7, 6, 2, 3, 7, 8, 7],
 [7, 8, 7, 6, 6, 4],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [3, 7, 3, 6, 2, 4],
 [6, 6, 2, 5, 3],
 [3, 5, 6, 9, 3, 7, 7],
 [5, 2, 2, 6, 2, 7],
 [9, 7, 4, 4, 4, 8],
 [2, 3, 5, 5],
 [4, 2, 4, 6, 3, 7],
 [5, 6, 6, 3, 7],
 [4, 6, 6, 3, 9],
 [6, 4, 5, 5, 3, 7],
 [4, 4, 4],
 [7, 6, 4, 8, 4],
 [5, 6, 6, 3, 7],
 [3, 2, 8, 4, 7],
 [3, 5, 6, 7, 3, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [2, 7, 6, 9, 6, 4, 6, 4],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [6, 2, 4, 6, 6, 3, 9],
 [6, 6, 7, 8, 6, 6],
 [8, 2, 5, 3, 6, 2, 4, 2],
 [4, 7, 3, 3, 7],
 [6, 6, 8, 2, 5],
 [6, 9, 3, 6, 7],
 [2, 6, 2, 2],
 [7, 6, 2, 5, 5],
 [5, 6, 6, 3, 7],
 [7, 8, 6, 6, 3],
 [3, 6, 7, 3],
 [2, 2, 9, 8, 3, 7],
 [2, 7, 6, 7, 2, 9],
 [3, 5, 6, 7, 3, 7],
 [2, 2, 6, 7, 6, 7],
 [6, 6, 6, 7, 3],
 [2, 2, 8, 8, 4, 7, 8, 2],
 [6, 2, 2, 6, 9],
 [3, 4, 8, 9, 4, 3, 7, 2, 5, 3],
 [2, 7, 8, 9],
 [7, 4, 2, 9],
 [4, 8, 3, 7, 6, 6],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [7, 6, 4, 8, 4],
 [7, 8, 3, 9, 2, 7, 8],
 [6, 4, 5, 5, 3, 7],
 [6, 2, 5, 2, 8, 4, 4, 5, 4, 6],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [2, 6, 5, 3, 6, 2, 6],
 [5, 7],
 [2, 7, 6, 9, 6],
 [2, 3, 6, 6, 3, 8, 8],
 [5, 6, 4, 6, 7, 6, 6],
 [4, 2, 9, 3, 7],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [3, 4, 9, 6, 6],
 [7, 6, 4, 8, 4],
 [7, 3, 5, 5, 3, 7, 7],
 [4, 7, 3, 3, 6],
 [7, 4, 2, 3],
 [4, 6, 6, 9, 2, 5, 3, 7],
 [2, 2, 7, 7, 6, 6],
 [2, 2, 7, 7],
 [7, 4, 2, 4],
 [7, 8, 7, 4],
 [8, 6, 7, 7, 3, 7],
 [6, 2, 2, 8, 5, 5, 6, 8, 4, 4],
 [7, 3, 7, 7, 2, 6, 6],
 [7, 3, 8, 3, 7, 7, 6, 6],
 [7, 3, 8, 3, 7, 7, 6, 6],
 [2, 8, 4, 5, 2],
 [2, 8, 6, 6, 4, 6, 4, 7],
 [4, 2, 7, 2, 4, 2],
 [6, 4, 8, 9, 3, 6],
 [4, 7, 2, 4, 2, 6],
 [5, 4, 6],
 [7, 3, 8, 3, 7, 7],
 [8, 3, 5, 2, 9, 7, 8, 3, 9],
 [9, 2, 7, 6, 3, 7],
 [7, 4, 6, 6, 6],
 [9, 7, 4, 4, 4, 8],
 [9, 4, 5, 5, 4, 6, 7, 6, 6],
 [4, 4, 4],
 [8],
 [7, 3, 3, 8, 3, 7],
 [7, 2, 6, 7, 7, 6, 6],
 [6, 6, 7, 7, 4, 7],
 [7, 2, 6, 3, 3, 7, 7],
 [8, 2, 5, 3, 6, 8, 4, 6, 3],
 [4, 2, 9, 6, 3, 7],
 [3, 6, 9, 5, 3, 7],
 [3, 7, 8, 7, 2, 3, 2],
 [3, 4, 4, 8, 3, 7, 6, 2],
 [2, 2, 7, 6, 3, 8, 8],
 [2, 7, 6, 9, 6],
 [6, 2, 5, 3, 6, 6, 2, 3, 6],
 [6, 2, 3, 6, 6, 2, 5, 3],
 [9, 2, 5, 5, 3, 7],
 [7, 2, 7, 7, 4, 7, 4],
 [7, 3, 9, 3, 7],
 [3, 3, 9, 2, 7, 3, 7],
 [2, 2, 4, 6],
 [5, 2, 6, 3],
 [2, 2, 7, 8, 3, 7],
 [6, 6, 7, 7, 4, 7],
 [6, 3, 5, 7, 6, 6],
 [5, 6, 6, 3, 7],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [4, 6, 6, 3, 9],
 [5, 6, 4, 6, 7, 6, 6],
 [3, 3, 9, 2, 7, 3, 7],
 [5, 3, 3, 3, 3, 7, 7, 6, 6],
 [2, 7, 3, 9, 3, 7],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [2, 7, 4, 2, 7],
 [3, 4, 3, 5, 3, 7],
 [7, 6, 4, 8, 4],
 [5, 7],
 [8, 2, 8, 3],
 [5, 6, 4, 4, 4, 8],
 [9, 2, 8, 7, 6, 6],
 [6, 2, 7, 7, 4, 2, 5, 5],
 [3, 2, 8, 4, 5, 2],
 [8, 2, 6, 2, 3],
 [7, 3, 9, 6, 6, 5, 3, 7],
 [7, 6, 4, 8, 4],
 [4, 3, 2, 3, 7, 8],
 [7, 2, 6, 2, 4, 3, 9],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [6, 2, 3, 2, 6, 4, 3, 5],
 [4, 2, 7, 2, 4, 2],
 [5, 6, 6, 3, 7],
 [2, 3, 7, 4],
 [3, 7, 9],
 [7, 3, 7, 7, 2, 6, 6],
 [6, 6, 6, 7, 6, 3],
 [2, 6, 9, 6, 2, 6],
 [9, 4, 5, 7, 6, 6],
 [5, 6, 7, 3, 9],
 [7, 7, 4, 6, 2, 3],
 [7, 4, 6, 7],
 [4, 6, 5, 3, 3, 6],
 [4, 2, 7, 7, 4, 7],
 [4, 2, 5, 5],
 [4, 8],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [9, 4, 5, 7, 6, 6],
 [6, 6, 7, 2],
 [3, 7, 8, 3, 7],
 [5, 7],
 [7, 4, 6, 7, 7, 6, 6],
 [4, 6, 6, 9, 2, 5, 3, 9],
 [6, 3, 5, 7, 6, 6],
 [2, 2, 2, 7, 3, 7, 2],
 [4, 2, 7, 2, 4, 2],
 [2, 6, 2, 4, 7, 2, 6],
 [9, 4, 4, 8, 3],
 [2, 5, 2, 2, 5],
 [7, 4, 8, 8, 3, 7],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [7, 4, 5, 8, 2],
 [2, 3, 6, 6, 3, 8, 8],
 [4, 3, 7, 7, 3, 7, 2],
 [6, 2, 3, 6, 6, 2, 5, 3],
 [7, 8, 3, 9, 2, 7, 8],
 [7, 5, 4, 6, 6, 3, 7],
 [2, 2, 7, 3, 3, 6, 2, 7],
 [4, 7, 4, 3, 3, 4, 6],
 [5, 3, 8, 9],
 [6, 3, 7, 2, 2, 3, 6],
 [5, 6, 4, 6, 7, 6, 6],
 [2, 2, 7, 8, 4, 5, 5, 6],
 [5, 6, 8, 3],
 [2, 7, 8, 9],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [6, 2, 8, 8, 4, 3, 9, 7],
 [2, 6, 5, 3, 6, 2, 6],
 [3, 4, 2, 5, 3, 7, 7, 6, 6],
 [4, 6, 7, 5, 4, 6, 7],
 [4, 2, 7, 7, 4, 7, 6, 6],
 [4, 2, 7, 7, 4, 7],
 [7, 2, 6, 8, 6, 7],
 [5, 4, 6],
 [8, 8, 7, 6, 3, 7],
 [6, 2, 5, 6, 6, 3],
 [3, 8, 2, 6, 7],
 [3, 7, 8, 7, 2, 3, 2],
 [5, 3, 9, 4, 7],
 [2, 9, 7, 3],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [6, 7, 2, 6, 7, 6, 3],
 [3, 6, 7, 2, 3, 7],
 [7, 6, 9, 3, 5, 5],
 [9, 6, 5, 3, 3],
 [6, 4, 8, 9, 3, 6],
 [7, 2, 9, 9, 3, 7],
 [5, 7],
 [7, 4, 2, 3],
 [2, 7, 6, 9, 6],
 [4, 3, 7, 7, 3, 7, 2],
 [2, 3, 6, 6, 3, 8, 8],
 [5, 4, 6, 4],
 [5, 6, 4, 6, 7, 6, 6],
 [7, 3, 2, 7, 7, 6, 6],
 [7, 2, 4, 8, 5, 8, 9],
 [9, 4, 5, 5, 4, 7],
 [2, 2, 7, 7, 6, 5, 5],
 [5, 3, 3, 3, 3, 7, 7, 6, 6],
 [2, 6, 3, 7, 3, 9, 7],
 [5, 7],
 [7, 6, 4, 8, 4],
 [2, 4, 8, 6, 4],
 [6, 8, 3, 5, 5, 3, 7],
 [6, 2, 4, 6, 8, 9, 7, 3],
 [2, 7, 6, 6, 5, 3],
 [6, 2, 7, 4, 3, 6],
 [6, 2, 6, 4, 5, 5, 2, 6],
 [2, 2, 7, 7, 6, 5, 5],
 [5, 6, 6, 3, 7],
 [3, 6, 7, 8, 3, 7],
 [6, 6, 6, 7, 3],
 [4, 2, 5, 5],
 [7, 3, 7, 3, 9],
 [5, 6, 4, 6, 7, 6, 6],
 [2, 2, 6, 6, 6, 6],
 [4, 4],
 [9, 2, 7, 6, 3, 7],
 [3, 6, 9, 5, 3],
 [2, 3, 6, 6, 3, 8, 8],
 [7, 6, 7, 8, 3, 7],
 [9, 4, 5, 7, 6, 6],
 [2, 7, 6, 7, 8, 7, 6, 6, 4],
 [8, 8, 7, 6, 3, 7],
 [3, 8, 7, 4, 2, 6],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [9, 4, 3, 3, 5, 3, 7],
 [5, 5, 3, 4, 6],
 [2, 7, 2, 9],
 [7, 3, 9, 3, 7],
 [4, 6, 6, 9, 2, 5, 3, 9],
 [2, 2, 7, 7],
 [2, 6, 3, 7, 3, 9, 7],
 [2, 7, 6, 9, 6],
 [5, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [9, 3, 5, 2, 4],
 [6, 2, 4, 8, 4, 7, 3],
 [6, 3, 5, 7, 6, 6],
 [5, 2, 6, 3, 7, 9],
 [4, 2, 7, 3, 4, 6, 4],
 [6, 2, 2, 7, 4, 3, 3],
 [4, 5, 6, 8, 3, 7],
 [5, 7, 2, 6, 3, 7],
 [2, 2, 7, 8, 4, 5, 5, 6],
 [7, 6, 4, 8, 4],
 [7, 2, 6, 2, 4, 3, 9],
 [4, 2, 7, 2, 4, 2],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [4, 8, 3, 7, 7, 3, 7, 6],
 [5, 6, 4, 6, 7, 6, 6],
 [7, 4, 2, 4, 6, 6, 6, 3],
 [2, 3, 5, 5],
 [4, 4, 5, 5],
 [4, 2, 9, 5, 4, 6, 7],
 [4, 2, 7, 2, 4, 2],
 [6, 2, 6, 3, 4, 5],
 [9, 7, 4, 4, 4, 8],
 [7, 2, 6, 2, 4, 3, 9],
 [4, 6, 6, 3, 9],
 [3, 8, 5, 3],
 [9, 7, 4, 4, 4, 8],
 [2, 2, 8, 3, 7],
 [9, 8],
 [9, 3, 4, 7, 7],
 [4, 8, 7, 7, 8],
 [4, 6, 6, 3, 9],
 [6, 2, 7, 7, 4, 2, 5, 5],
 [7, 2, 6, 6, 7],
 [4, 2, 6, 7, 3, 6],
 [7, 2, 6, 4, 7, 3, 9],
 [8, 2, 8, 4, 4, 2, 6],
 [2, 6, 9, 3],
 [4, 2, 7, 7, 3, 5, 5],
 [4, 4],
 [2, 8, 8, 5, 3, 7],
 [8, 8, 7, 6, 3, 7],
 [4, 2, 6, 4, 5, 8, 6, 6],
 [2, 8, 7, 4, 3, 7, 7],
 [6, 3, 5, 7, 6, 6],
 [3, 2, 8, 5, 5, 6, 3, 7],
 [9, 2, 8, 7, 6, 6],
 [9, 2, 8, 7, 6, 6],
 [2, 5, 2, 2, 5],
 [7, 6, 7, 2, 5, 3, 7],
 [7, 4, 2, 4],
 [3, 8, 6, 6],
 [7, 6, 9, 3, 5, 5],
 [7, 4, 4, 5, 5, 4, 7, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [5, 6, 4, 6, 7, 6, 6],
 [5, 9, 6, 2, 4],
 [7, 4, 2, 7, 7],
 [2, 7, 6, 7, 8, 7, 6, 6, 4],
 [2, 7, 6, 9, 6],
 [6, 4, 5, 5, 3, 7],
 [7, 3, 8, 3, 7, 7, 6, 6],
 [2, 2, 7, 5, 3, 7],
 [9, 3, 7, 8],
 [2, 9, 2, 5, 2],
 [6, 2, 2, 2, 7, 8, 4, 9],
 [7, 8, 2, 4, 6],
 [5, 7],
 [3, 4, 4, 8, 3, 7, 6, 2],
 [7, 2, 6, 2, 4, 3, 9],
 [5, 6, 6, 3, 7],
 [7, 6, 2, 3, 7, 8, 7],
 [4, 2, 7, 7, 4, 6, 4, 8, 6, 6],
 [2, 8, 3, 8, 2, 7],
 [7, 8, 2, 4, 6],
 [4, 6, 6, 3, 9, 4, 6],
 [9, 6, 6, 3],
 [2, 2, 5, 3, 7],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [7, 6, 9, 3, 7, 7],
 [5, 6, 9, 2, 6, 6],
 [6, 2, 6, 2, 4, 6, 6],
 [6, 3, 5, 7, 6, 6],
 [4, 2, 9, 3, 7],
 [7, 8, 2, 4, 6],
 [7, 3, 7, 3, 9],
 [7, 6, 7, 8, 3, 7],
 [8, 8, 7, 6, 3, 7],
 [4, 8, 6, 8],
 [7, 2, 6, 4, 7, 3, 9],
 [7, 2, 6, 4, 7, 3, 9],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [5, 6, 4, 6, 7, 8, 6, 6],
 [6, 4, 5, 5, 7],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [6, 6, 6, 7, 3],
 [7, 4, 2, 4, 2, 7, 3, 7, 6, 6],
 [6, 2, 2, 6, 9],
 [7, 6, 4, 8, 4],
 [4, 8, 3, 3],
 [3, 2, 8, 4, 7],
 [2, 7, 6, 7, 8, 7, 6, 6, 4],
 [2, 3, 7, 4, 3, 7],
 [7, 2, 4, 6, 4, 3, 8],
 [7, 4, 3, 7, 2, 3],
 [6, 2, 7, 8, 4, 6, 3, 9],
 [4, 8, 3, 3],
 [5, 4, 6, 4],
 [7, 8, 7, 7, 6],
 [7, 6, 9, 3, 5, 5],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [9, 4, 4, 8, 3],
 [5, 6, 4, 6, 7, 6, 6],
 [4, 3, 6, 8, 7, 9],
 [9, 2, 5, 5, 3, 7],
 [4, 2, 5, 3],
 [3, 6, 9, 5, 3, 7],
 [4, 2, 5, 3],
 [6, 5, 4, 8, 3, 7],
 [8, 4, 5, 5, 2],
 [5, 6, 2, 4],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [3, 8, 2, 6, 7],
 [9, 2, 8, 7, 6, 6],
 [7, 9, 2, 6, 7, 6, 6],
 [6, 6, 6, 7, 3],
 [7, 6, 4, 8, 4],
 [5, 6, 6, 3, 7],
 [7, 3, 7, 3, 9],
 [2, 6, 6, 8, 7, 3, 7, 2, 7],
 [6, 2, 7, 7, 3, 9],
 [7, 7, 8, 4, 8, 8],
 [9, 4, 3, 3, 5, 3, 7],
 [2, 2, 5, 3, 7],
 [3, 4, 6, 5, 3, 9],
 [2, 2, 7, 8, 3, 7],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [7, 6, 4, 8, 4],
 [3, 4, 8, 9, 4, 3, 7, 2, 5, 3],
 [7, 9, 2, 6, 7, 6, 6],
 [6, 7, 8, 4, 9],
 [7, 8, 7, 4],
 [7, 2, 8, 3, 5],
 [2, 7, 6, 9, 6],
 [5, 4, 8, 8, 5, 3],
 [9, 2, 8, 3, 7, 7],
 [2, 6, 5, 3, 6, 2, 6],
 [4, 4, 5, 3, 7],
 [4, 7, 2, 9],
 [2, 2, 5, 3, 7],
 [7, 6, 4, 8, 4],
 [7, 2, 7, 6, 8, 7, 7, 3, 6],
 [7, 3, 8, 3, 7, 7],
 [8, 6, 7, 7, 3, 7],
 [3, 6, 6, 4, 6, 4, 8, 3, 9],
 [3, 2, 8, 4, 7],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [4, 8, 9, 6, 4],
 [7, 8, 4, 4],
 [4, 6, 6, 3],
 [3, 8, 7, 4, 2, 6],
 [6, 9, 3, 6],
 [6, 3, 3, 4, 6, 2],
 [7, 8, 2, 6, 8, 6, 6],
 [6, 4, 5, 5, 3, 7],
 [6, 2, 6, 6, 6, 6, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [8, 7, 2, 6],
 [7, 6, 6, 3, 7, 6],
 [6, 2, 5, 4, 6, 6, 3, 9],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [9, 4, 5, 5, 3, 7, 7, 6, 6],
 [3, 2, 8, 4, 7],
 [3, 2, 8, 4, 7],
 [6, 6, 7, 7, 4, 7],
 [2, 6, 9, 3, 7],
 [7, 4, 2, 4, 2, 7, 3, 7],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [7, 6, 9, 3, 5, 5],
 [7, 8, 3, 9, 2, 7, 8],
 [5, 7],
 [4, 2, 5, 5, 2, 4, 4, 3, 7],
 [7, 3, 9, 6, 6, 5, 3, 7],
 [7, 6, 2, 3, 7, 8, 7, 6, 6],
 [7, 7, 8, 4, 8, 8],
 [5, 6, 7, 3, 9],
 [2, 2, 5, 5],
 [2, 6, 6, 7, 2, 3],
 [7, 4, 6, 7],
 [3, 4, 7, 2, 4, 3, 7],
 [7, 6, 5, 5, 2, 7, 3],
 [5, 6, 6, 3, 7],
 [6, 3, 9, 3, 7],
 [9, 4, 5, 7, 6, 6],
 [6, 6, 6, 7, 3],
 [4, 6, 5, 3, 3, 6],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [6, 2, 5, 3, 6, 6, 2, 3, 6],
 [9, 6, 8, 6, 4],
 [5, 4, 6, 4],
 [2, 8, 5, 4, 6, 7],
 [2, 4, 7, 4, 7, 8, 3, 6, 7, 3, 6],
 [4, 8, 5, 5],
 [9, 6, 8, 6, 4],
 [2, 3, 6, 6, 3, 8, 8],
 [3, 6, 9, 5, 3, 7],
 [5, 7],
 [5, 2, 7, 7, 6, 6],
 [4, 2, 9, 5, 4, 6, 7],
 [3, 8, 5, 3],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [5, 6, 4, 6, 7, 6, 6],
 [4, 2, 7, 7, 4, 7, 6, 6],
 [2, 8, 2, 4, 2, 6, 2, 6],
 [5, 6, 4, 6, 7, 6, 6],
 [6, 6, 7, 7, 6, 9],
 [4, 2, 7, 7, 4, 7, 6, 6],
 [4, 4],
 [3, 5, 6, 7, 3, 7],
 [6, 3, 9, 8, 6, 6],
 [9, 4, 4, 8, 3],
 [4, 2, 5, 5],
 [9, 2, 8, 5, 4, 6, 7],
 [4, 4, 2, 5, 7],
 [6, 4, 8, 9, 3, 6],
 [2, 4, 2, 6, 3, 5, 3, 7],
 [9, 6, 8, 6, 4],
 [3, 2, 9],
 [3, 2, 8, 4, 4, 3, 7, 8, 9],
 [4, 2, 6, 7, 3, 6],
 [7, 2, 6, 3, 6, 5, 7, 4],
 [4, 8, 3, 7, 7, 3, 7, 6],
 [5, 3, 7, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [5, 6, 6, 3, 7],
 [4, 6, 3, 3, 6, 2, 6],
 [5, 7],
 [3, 6, 3, 7, 6, 6],
 [2, 4, 2, 8, 3, 9],
 [3, 6, 9, 6, 7],
 [9, 4, 5, 7, 6, 6],
 [2, 8, 7, 5, 3],
 [5, 3, 7, 8, 3, 7],
 [2, 4, 3, 7, 7, 9],
 [2, 8, 6, 6, 4, 6, 4, 7],
 [2, 4, 2, 6],
 [9, 4, 4, 8, 3],
 [4, 6, 8, 5, 3],
 [2, 8, 3, 7, 9],
 [6, 2, 7, 4],
 [4, 6, 7, 5, 4, 6, 7],
 [2, 5, 3, 6, 3, 6, 8, 7],
 [9, 2, 7, 3],
 [2, 2, 7, 5, 7, 6, 6],
 [3, 6, 9],
 [9, 2, 8, 8, 7],
 [6, 4, 8, 9, 3, 6],
 [3, 2, 8, 4, 7],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [4, 6, 3, 4, 3, 7],
 [7, 6, 9, 3, 3, 7],
 [2, 2, 5, 3, 7],
 [6, 4, 5, 5, 3, 7],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [2, 2, 6, 7, 2, 3, 5, 5],
 [2, 7, 6, 6, 5, 3],
 [7, 2, 6, 2, 4, 3, 9],
 [7, 4, 6, 7],
 [5, 7],
 [2, 6, 9],
 [7, 4, 4, 5, 5, 4, 7, 7],
 [5, 6, 6, 3, 7],
 [9, 8],
 [7, 6, 8, 8, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [7, 4, 2, 3],
 [4, 8, 3, 3, 6, 2, 6],
 [7, 8, 6, 6, 3],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [6, 6, 7, 7, 4, 7, 6, 6],
 [4, 4, 4],
 [4, 2, 7, 9, 2],
 [2, 3, 6, 6, 3, 8, 8],
 [5, 6, 6, 3, 7],
 [7, 4, 3, 7, 2, 3],
 [7, 3, 7, 3, 9],
 [4, 7, 2, 4, 2, 6],
 [6, 4, 3, 3, 5, 3, 8, 6, 6],
 [3, 6, 7, 8, 3, 7],
 [2, 6, 5, 3, 6, 2, 6],
 [2, 8, 2, 5],
 [2, 8, 7, 7, 9],
 [9, 2, 5, 5, 3, 7],
 [7, 2, 6, 8, 4, 2, 4, 6],
 [2, 6, 5, 5, 4, 6, 7],
 [7, 8, 6, 6, 3],
 [2, 2, 5, 3, 9, 4, 6],
 [4, 2, 9, 5, 4, 6, 7],
 [6, 6, 6, 7, 3],
 [6, 5, 7, 6, 6],
 [2, 7, 8, 9],
 [4, 2, 7, 2, 4, 2],
 [7, 3, 9, 3, 7],
 [2, 2, 7, 2, 3, 7],
 [5, 6, 6, 3, 7],
 [2, 2, 6, 7, 2, 3, 5, 5],
 [5, 6, 9, 3],
 [9, 3, 2, 8, 3, 7],
 [6, 6, 7, 7, 4, 7],
 [9, 2, 6, 4],
 [6, 4, 8, 9, 3, 6],
 [7, 2, 6, 3, 3, 7, 7],
 [6, 6, 5, 4, 6, 2],
 [6, 6, 7, 7, 4, 7],
 [4, 6, 6, 9, 2, 5, 3, 7],
 [4, 7, 4, 3, 3, 4, 6],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [5, 7],
 [5, 6, 6, 4],
 [7, 2, 6, 2, 4, 3, 9],
 [7, 6, 6, 9],
 [3, 7, 7, 4, 6, 6, 9, 2],
 [9, 6, 6, 3],
 [2, 8, 6, 6, 4, 6, 4, 4, 2, 6],
 [5, 3, 6, 6, 4, 6, 4, 7],
 [4, 8, 9, 6, 4],
 [6, 2, 3, 6, 6, 2, 5, 3],
 [4, 2, 7, 7, 4, 7],
 [7, 8, 3, 9, 2, 7, 8],
 [5, 3, 6, 6, 3, 3, 9],
 [9, 2, 5, 8, 6, 6],
 [2, 3, 6, 6, 3, 8, 8],
 [2, 8, 6, 6, 4, 6, 4, 4, 2, 6],
 [7, 7, 8, 4, 8, 8],
 [2, 2, 7, 8, 6, 6],
 [3, 2, 8, 4, 7],
 [6, 2, 7, 4],
 [2, 2, 5, 3, 7],
 [5, 4, 6, 4],
 [6, 2, 7, 8, 4, 6, 3, 9],
 [6, 3, 3, 4, 6, 2],
 [6, 6, 6, 3, 9],
 [9, 2, 8, 7, 6, 6],
 [2, 6, 5, 5, 4, 6, 7],
 [4, 4],
 [7, 4, 2, 9],
 [9, 6, 6, 4],
 [2, 8, 7, 6, 3, 8, 8],
 [4, 2, 7, 3, 4, 6],
 [2, 7, 6, 9, 6],
 [9, 4, 5, 7, 6, 6],
 [2, 2, 6, 2, 2, 4, 6],
 [5, 4, 6, 3, 6, 3, 9],
 [5, 2, 6],
 [2, 3, 2, 6, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [3, 5, 6, 9, 3],
 [6, 8, 7, 7, 4, 9],
 [3, 8, 3, 6, 8, 3, 7],
 [7, 8, 2, 7, 3, 9],
 [6, 4, 5, 5, 3, 7],
 [6, 6, 6, 7, 3],
 [6, 2, 2, 6, 9],
 [2, 2, 4, 6],
 [6, 2, 7, 7, 4],
 [7, 2, 6, 4, 7, 3, 9],
 [7, 4, 2, 4, 2, 7, 3, 7, 6, 6],
 [7, 3, 9, 3, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [9, 2, 8, 7, 6, 6],
 [7, 2, 9, 9, 3, 7],
 [4, 8, 6, 8],
 [5, 3, 9, 4, 7],
 [2, 6, 6, 6, 3, 7],
 [5, 4, 8],
 [4, 8, 6, 8],
 [5, 6, 4, 4, 4, 8],
 [7, 6, 9, 3, 5, 5],
 [9, 4, 5, 3, 9],
 [9, 6, 8, 6, 4],
 [4, 6, 3, 4, 3, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [2, 5, 8, 2, 7, 2, 3, 6],
 [7, 3, 7, 3, 9],
 [3, 7, 3, 3, 6, 2, 6],
 [2, 9, 7, 3],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [7, 6, 4, 8, 4],
 [3, 6, 7, 3],
 [6, 5, 7, 3, 6],
 [7, 2, 6, 4, 7, 3, 9],
 [7, 6, 4, 8, 4],
 [4, 7, 2, 9],
 [4, 2, 9, 3, 7],
 [6, 2, 2, 5, 8, 7, 3],
 [7, 6, 2, 3, 7, 8, 7, 6, 6],
 [9, 6, 5, 3],
 [6, 2, 6, 6],
 [2, 7, 8, 9],
 [7, 6, 4, 8, 4],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [4, 6, 8, 7, 8, 6, 6],
 [2, 3, 2, 5, 3, 7],
 [2, 7, 6, 9, 6],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [7, 6, 4, 8, 4],
 [4, 4, 2, 7, 6, 6],
 [5, 7],
 [3, 8, 6, 2, 2, 6],
 [8, 6, 7, 7, 3, 7],
 [7, 6, 4, 8, 4],
 [5, 5, 4, 6, 3],
 [4, 2, 9, 5, 4, 6, 7],
 [2, 2, 7, 6, 3, 7],
 [6, 2, 4, 6, 6, 3, 9],
 [7, 2, 8, 8, 3, 7, 7, 6, 6],
 [2, 6, 6, 5],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [7, 6, 4, 8, 4],
 [7, 3, 8, 3, 7, 7, 6, 6],
 [7, 6, 4, 3, 7, 7],
 [7, 3, 5, 5, 3, 7, 7],
 [5, 6, 2, 7, 7],
 [4, 6, 2, 2, 7],
 [4, 4, 4],
 [8, 3, 5, 2, 7, 7, 8, 3, 9],
 [9, 4, 5, 7, 6, 6],
 [5, 6, 4, 6, 7, 6, 6],
 [3, 5, 6, 7, 3, 7],
 [3, 6, 7, 7, 3, 9],
 [6, 4, 5, 5, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [2, 6, 2, 4, 7, 2, 6],
 [4, 4],
 [7, 4, 6, 7, 7, 6, 6],
 [7, 8, 8, 8, 6, 6],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [4, 2, 7, 3, 6, 3, 7],
 [4, 3, 6, 3, 7, 4, 9],
 [3, 8, 3, 6, 8, 3, 7],
 [9, 4, 4, 8, 3],
 [2, 4, 8, 4, 7, 7, 3],
 [7, 6, 4, 8, 4],
 [2, 4, 2, 6, 4],
 [9, 4, 4, 8, 3],
 [2, 2, 7, 7, 4, 5, 5, 6],
 [4, 8, 2, 2, 2, 7, 3],
 [7, 3, 8, 3, 7, 7],
 [6, 2, 7, 8, 4, 6, 3, 9],
 [3, 4, 3, 5, 3, 7],
 [3, 4, 3, 5, 3, 7],
 [2, 6, 6, 6, 3, 7],
 [2, 8, 7, 4, 3, 7, 7],
 [6, 3, 6, 6, 6, 3, 5, 5],
 [6, 8, 7, 7, 2, 9],
 [4, 8, 3, 7, 7, 3, 7, 6],
 [4, 2, 6, 4, 5, 8, 6, 6],
 [9, 3, 5, 5, 7],
 [7, 4, 2, 7, 7],
 [4, 4, 4, 4, 4, 6, 7],
 [8, 6, 7, 7, 3, 7],
 [6, 3, 5, 7, 6, 6],
 [6, 2, 7, 4, 3, 6],
 [6, 2, 2, 2, 7, 8, 4, 9],
 [5, 6, 4, 6, 7, 6, 6],
 [4, 6, 6, 3, 9],
 [3, 2, 8, 4, 7],
 [7, 2, 4, 2, 3, 3, 3, 7],
 [4, 2, 7, 2, 4, 2],
 [3, 5, 5, 4, 6, 8, 8],
 [7, 4, 6, 7],
 [9, 2, 7, 3],
 [7, 8, 6, 8, 8],
 [9, 6, 8, 6, 4],
 [5, 7],
 [7, 3, 7, 3, 9],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [2, 3, 5, 5],
 [3, 4, 2, 9],
 [7, 7, 2, 8, 8],
 [2, 2, 9, 8, 3, 7],
 [7, 6, 4, 8, 4],
 [7, 2, 6, 2, 4, 3, 9],
 [2, 3, 2, 5, 3, 7],
 [2, 4, 7, 3],
 [3, 2, 8, 4, 7],
 [3, 3, 7, 7, 3, 5, 5],
 [9, 6, 8, 6, 4],
 [4, 4, 4, 4, 4, 6, 7],
 [6, 4, 8, 9, 3, 6],
 [2, 2, 6, 7, 2, 3, 5, 5],
 [5, 6, 7, 3, 9],
 [6, 9, 3, 7, 7],
 [7, 4, 3, 5, 8, 6, 6],
 [4, 3, 7, 6, 2, 6, 3, 3, 9],
 [7, 8, 4, 9],
 [5, 7],
 [5, 6, 4, 6, 7, 6, 6],
 [2, 7, 6, 6, 5, 7],
 [4, 8, 6, 8],
 [5, 6, 4, 6, 7, 6, 6],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [5, 2, 6, 4],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [3, 4, 4, 8, 3, 7, 6, 2],
 [4, 4, 4],
 [9, 2, 8, 8, 7],
 [4, 2, 9, 3, 7],
 [5, 6, 6, 3, 7],
 [7, 2, 6, 4, 7, 3, 9],
 [2, 6, 5, 5, 4, 6, 7],
 [6, 9, 3, 7, 7],
 [7, 8, 6, 8, 8],
 [7, 8, 3, 9, 2, 7, 8],
 [3, 2, 8, 4, 7],
 [4, 4],
 [5, 8, 8, 9],
 [4, 2, 5, 5],
 [3, 6, 7, 8, 3, 7],
 [9, 6, 8, 6, 4],
 [3, 2, 8, 4, 7],
 [6, 2, 7, 7, 4],
 [2, 9, 7, 3],
 [4, 3, 7, 7, 3, 7, 2],
 [9, 7, 4, 4, 4, 8],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [6, 6, 6, 3, 9],
 [7, 6, 4, 8, 4],
 [3, 7, 3, 6, 2, 4],
 [8, 8, 7, 6, 3, 7],
 [5, 7],
 [2, 7, 6, 9, 6],
 [7, 3, 7, 3, 9],
 [2, 6, 9, 3, 6],
 [4, 2, 5, 5],
 [7, 6, 6, 5, 3],
 [9, 2, 8, 5, 4, 6, 7],
 [2, 2, 7, 8, 6, 6],
 [4, 7, 2, 9],
 [7, 4, 6, 6, 6, 6, 7],
 [2, 2, 7, 7, 3, 6, 8, 3, 7],
 [3, 5, 5, 4, 6, 8, 8],
 [9, 2, 5, 5, 3, 7],
 [5, 6, 6, 3, 7],
 [4, 4, 2, 7, 6, 6],
 [2, 5, 2, 7, 5],
 [7, 2, 6, 4, 7, 3, 9],
 [5, 7],
 [2, 3, 6, 6, 3, 8, 8],
 [7, 2, 7, 5, 7],
 [5, 7],
 [9, 2, 3, 3],
 [4, 2, 7, 7, 4, 7],
 [6, 4, 5, 5, 7],
 [6, 3, 6, 3, 6, 9, 2],
 [9, 3, 3, 5, 7],
 [4, 7, 3, 3, 6],
 [7, 3, 9, 3, 7],
 [4, 2, 7, 7, 4, 7],
 [6, 6, 6, 8, 6, 9, 2],
 [3, 2, 8, 4, 7],
 [7, 2, 6, 2, 4, 3, 9],
 [2, 2, 5, 5],
 [3, 6, 7, 8, 3, 7],
 [6, 5, 7, 6, 6],
 [3, 4, 8, 9, 4, 3, 7, 2, 5, 3],
 [3, 4, 7, 2, 4, 3, 7],
 [9, 2, 6, 4],
 [5, 6, 7, 3, 9],
 [6, 2, 7, 4, 3, 6],
 [4, 8, 6, 7, 4, 7, 3, 9],
 [9, 4, 6, 8, 3, 7, 7],
 [2, 2, 7, 8, 3, 7],
 [6, 8, 3, 5, 5, 3, 7],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [9, 2, 8, 7, 6, 6],
 [6, 6, 7, 2, 6],
 [2, 2, 7, 7, 6, 5, 5],
 [6, 3, 5, 7, 6, 6],
 [4, 2, 6, 4, 5, 8, 6, 6],
 [9, 4, 4, 8, 3],
 [8, 2, 5, 3, 3, 9],
 [2, 2, 5, 3, 7],
 [7, 4, 6, 4, 5, 3, 8, 6, 6],
 [7, 6, 4, 8, 4],
 [7, 8, 4, 9],
 [7, 7, 2, 7, 5, 7],
 [3, 8, 3, 3, 9],
 [8, 8, 7, 6, 3, 7],
 [2, 7, 6, 6, 5, 7],
 [2, 2, 7, 6, 3, 7],
 [7, 6, 5, 4, 7],
 [2, 6, 9, 3],
 [7, 6, 4, 3, 7, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [7, 2, 6, 4, 3, 5],
 [9, 7, 4, 4, 4, 8],
 [6, 6, 6, 3, 9],
 [7, 2, 6, 4, 7, 3, 9],
 [2, 6, 6, 7, 3, 7],
 [5, 7],
 [2, 7, 6, 9, 6],
 [2, 7, 6, 9, 6],
 [8, 4, 6, 6, 7, 7, 6, 6],
 [9, 4, 5, 7, 6, 6],
 [2, 8, 7, 6, 7],
 [7, 2, 8, 3, 5],
 [7, 2, 4, 6, 4, 3, 8],
 [4, 2, 7, 7, 4, 7],
 [5, 7],
 [2, 7, 2, 4, 3, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [2, 2, 5, 3, 7],
 [5, 6, 6, 4],
 [4, 4, 2, 5, 7],
 [5, 2, 7, 7, 3, 6],
 [2, 6, 3, 3, 7, 7, 6, 6],
 [5, 7, 8, 3, 4, 3, 7],
 [7, 6, 5, 5, 4, 6, 7],
 [7, 6, 9, 3, 3, 7],
 [2, 5, 2, 7, 5],
 [8, 6, 9, 6, 7, 3, 6, 3],
 [7, 6, 3, 7, 4, 4, 8, 3, 9],
 [2, 6, 5, 6, 6],
 [6, 2, 7, 8, 4, 6, 3, 9],
 [6, 2, 7, 8, 4, 6, 3, 9],
 [2, 8, 6, 6, 4, 6, 4, 4, 2, 6],
 [3, 6, 6, 4, 6, 4, 8, 3, 9],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [8, 3, 4, 2],
 [4, 4, 5, 5],
 [9, 4, 5, 7, 6, 6],
 [4, 8, 4, 4, 3, 7],
 [6, 9, 3, 6],
 [7, 8, 5, 5, 4, 8, 2, 6],
 [7, 6, 6, 2, 6],
 [6, 4, 5, 5, 3, 7],
 [2, 3, 7, 7, 9],
 [7, 3, 7, 3, 9],
 [4, 8, 4, 4, 3, 7],
 [6, 4, 5, 5, 7],
 [9, 4, 5, 5, 4, 2, 6, 7],
 [2, 2, 5, 3, 7],
 [6, 3, 5, 7, 6, 6],
 [5, 2, 2, 6, 2, 7],
 [5, 4, 6, 3, 6, 3, 9],
 [5, 7],
 [7, 6, 2, 4, 6, 7, 6, 6],
 [2, 2, 6, 6, 6, 6],
 [4, 2, 7, 2, 4, 2],
 [6, 2, 5, 2, 8, 4, 4, 5, 4, 6],
 [7, 8, 3, 8, 3, 6, 7],
 [3, 2, 8, 4, 7],
 [4, 2, 7, 7, 3, 5, 5],
 [2, 4, 2, 8, 3, 9],
 [8, 6, 7, 7, 3, 7],
 [2, 2, 9, 8, 3, 7],
 [9, 4, 5, 5, 4, 2, 6, 7, 6, 6],
 [6, 6, 6, 8, 6, 9, 2],
 [6, 4, 5, 5, 3, 7],
 [3, 5, 3, 6, 4, 6, 4],
 [4, 8, 3, 3, 6, 2, 6],
 [5, 6, 6, 3, 7],
 [7, 2, 6, 4, 3, 5],
 [2, 6, 5, 3, 6, 2, 6],
 [4, 6, 8, 7, 3],
 [7, 8, 8, 8, 6, 6],
 [7, 8, 4, 9],
 [9, 3, 5, 5, 7],
 [3, 6, 7, 7, 3, 9],
 [7, 4, 2, 3],
 [3, 5, 6, 7, 3, 7],
 [6, 6, 6, 7, 3],
 [4, 2, 5, 5],
 [3, 2, 8, 4, 7],
 [6, 5, 7, 6, 6],
 [2, 3, 2, 6, 7],
 [4, 3, 7, 7, 4, 6, 4],
 [2, 4, 2, 8, 3, 9],
 [6, 2, 4, 3, 3],
 [5, 7],
 [2, 4, 8, 4, 7, 7, 3],

In [64]:
len(number_list)

11080

In [74]:
df.head()

,customerid,name,address,citystatezip,birthdate,phone,phone_clean,last_name,phone_by_name
0,1001,Jack Quinn,201 E Park St,"Los Angeles, CA 91343",1960-05-14,805-287-8515,8052878515,"[, q, u, i, n, n, ]",78466
1,1002,David Powell,224C Tysens Ln,"Staten Island, NY 10306",1978-04-04,516-768-1652,5167681652,"[, p, o, w, e, l, l, ]",769355
2,1003,Carrie Green,1608 W 53rd Way,"Tampa, FL 33614",1969-01-21,727-209-0470,7272090470,"[, g, r, e, e, n, ]",47336
3,1004,Steven Miller,178½ E 7th St,"Manhattan, NY 10009",1953-08-17,607-941-9563,6079419563,"[, m, i, l, l, e, r, ]",645537
4,1005,Christine Powers,270 W 242nd St,"Bronx, NY 10463",1983-06-06,212-759-9043,2127599043,"[, p, o, w, e, r, s, ]",769377

In [66]:
num_join_list = []
for phone_num in number_list:
    if phone_num == '':
        pass
    else:
       num_join_list.append(''.join(map(str, phone_num)))

In [67]:
num_join_list

['78466',
 '769355',
 '47336',
 '645537',
 '769377',
 '7264739',
 '2655467',
 '7838367',
 '369537',
 '5646766',
 '27696',
 '925537',
 '2665',
 '7467',
 '22672355',
 '66673',
 '76484',
 '7838367',
 '667747',
 '72757',
 '974448',
 '242839',
 '9285467',
 '425826',
 '242839',
 '442766',
 '7623787',
 '787664',
 '78554826',
 '373624',
 '66253',
 '3569377',
 '522627',
 '974448',
 '2355',
 '424637',
 '56637',
 '46639',
 '645537',
 '444',
 '76484',
 '56637',
 '32847',
 '356737',
 '94554267',
 '27696464',
 '76246766',
 '6246639',
 '667866',
 '82536242',
 '47337',
 '66825',
 '69367',
 '2622',
 '76255',
 '56637',
 '78663',
 '3673',
 '229837',
 '276729',
 '356737',
 '226767',
 '66673',
 '22884782',
 '62269',
 '3489437253',
 '2789',
 '7429',
 '483766',
 '437626339',
 '76484',
 '7839278',
 '645537',
 '6252844546',
 '76246766',
 '2653626',
 '57',
 '27696',
 '2366388',
 '5646766',
 '42937',
 '763744839',
 '34966',
 '76484',
 '7355377',
 '47336',
 '7423',
 '46692537',
 '227766',
 '2277',
 '7424',
 '7874',
 '867737',
 '6228556844',
 '7377266',
 '73837766',
 '73837766',
 '28452',
 '28664647',
 '427242',
 '648936',
 '472426',
 '546',
 '738377',
 '835297839',
 '927637',
 '74666',
 '974448',
 '945546766',
 '444',
 '8',
 '733837',
 '7267766',
 '667747',
 '7263377',
 '825368463',
 '429637',
 '369537',
 '3787232',
 '34483762',
 '2276388',
 '27696',
 '625366236',
 '62366253',
 '925537',
 '7277474',
 '73937',
 '3392737',
 '2246',
 '5263',
 '227837',
 '667747',
 '635766',
 '56637',
 '26337766',
 '46639',
 '5646766',
 '3392737',
 '533337766',
 '273937',
 '437626339',
 '27427',
 '343537',
 '76484',
 '57',
 '8283',
 '564448',
 '928766',
 '62774255',
 '328452',
 '82623',
 '73966537',
 '76484',
 '432378',
 '7262439',
 '94554267',
 '62326435',
 '427242',
 '56637',
 '2374',
 '379',
 '7377266',
 '666763',
 '269626',
 '945766',
 '56739',
 '774623',
 '7467',
 '465336',
 '427747',
 '4255',
 '48',
 '84667766',
 '945766',
 '6672',
 '37837',
 '57',
 '7467766',
 '46692539',
 '635766',
 '2227372',
 '427242',
 '2624726',
 '94483',
 '25225',
 '748837',
 '763744839',
 '74582',
 '2366388',
 '4377372',
 '62366253',
 '7839278',
 '7546637',
 '22733627',
 '4743346',
 '5389',
 '6372236',
 '5646766',
 '22784556',
 '5683',
 '2789',
 '94554267',
 '62884397',
 '2653626',
 '342537766',
 '4675467',
 '42774766',
 '427747',
 '726867',
 '546',
 '887637',
 '625663',
 '38267',
 '3787232',
 '53947',
 '2973',
 '437626339',
 '6726763',
 '367237',
 '769355',
 '96533',
 '648936',
 '729937',
 '57',
 '7423',
 '27696',
 '4377372',
 '2366388',
 '5464',
 '5646766',
 '7327766',
 '7248589',
 '945547',
 '2277655',
 '533337766',
 '2637397',
 '57',
 '76484',
 '24864',
 '6835537',
 '62468973',
 '276653',
 '627436',
 '62645526',
 '2277655',
 '56637',
 '367837',
 '66673',
 '4255',
 '73739',
 '5646766',
 '226666',
 '44',
 '927637',
 '36953',
 '2366388',
 '767837',
 '945766',
 '276787664',
 '887637',
 '387426',
 '763744839',
 '9433537',
 '55346',
 '2729',
 '73937',
 '46692539',
 '2277',
 '2637397',
 '27696',
 '57',
 '5646766',
 '93524',
 '6248473',
 '635766',
 '526379',
 '4273464',
 '6227433',
 '456837',
 '572637',
 '22784556',
 '76484',
 '7262439',
 '427242',
 '84667766',
 '48377376',
 '5646766',
 '74246663',
 '2355',
 '4455',
 '4295467',
 '427242',
 '626345',
 '974448',
 '7262439',
 '46639',
 '3853',
 '974448',
 '22837',
 '98',
 '93477',
 '48778',
 '46639',
 '62774255',
 '72667',
 '426736',
 '7264739',
 '8284426',
 '2693',
 '4277355',
 '44',
 '288537',
 '887637',
 '42645866',
 '2874377',
 '635766',
 '32855637',
 '928766',
 '928766',
 '25225',
 '7672537',
 '7424',
 '3866',
 '769355',
 '74455477',
 '5646766',
 '5646766',
 '59624',
 '74277',
 '276787664',
 '27696',
 '645537',
 '73837766',
 '227537',
 '9378',
 '29252',
 '62227849',
 '78246',
 '57',
 '34483762',
 '7262439',
 '56637',
 '7623787',
 '4277464866',
 '283827',
 '78246',
 '4663946',
 '9663',
 '22537',
 '84667766',
 '769377',
 '569266',
 '6262466',
 '635766',
 '42937',
 '78246',
 '73739',
 '767837',
 '887637',
 '4868',
 '7264739',
 '7264739',
 '94554267',
 '56467866',
 '64557',
 '78554826',
 '66673',
 '7424273766',
 '62269',
 '76484',
 '4833',
 '32847',
 '276787664',
 '237437',
 '7246438',
 '743723',
 '62784639',
 '4833',
 '5464',
 '78776',
 '769355',
 '437626339',
 '94483',
 '5646766',
 '436879',
 '925537',
 '4253',
 '369537',
 '4253',
 '654837',
 '84552',
 '5624',
 '78554826',
 '38267',
 '928766',
 '7926766',
 '66673',
 '76484',
 '56637',
 '73739',
 '266873727',
 '627739',
 '778488',
 '9433537',
 '22537',
 '346539',
 '227837',
 '763744839',
 '76484',
 '3489437253',
 '7926766',
 '67849',
 '7874',
 '72835',
 '27696',
 '548853',
 '928377',
 '2653626',
 '44537',
 '4729',
 '22537',
 '76484',
 '727687736',
 '738377',
 '867737',
 '366464839',
 '32847',
 '437626339',
 '48964',
 '7844',
 '4663',
 '387426',
 '6936',
 '633462',
 '7826866',
 '645537',
 '6266667',
 '94554267',
 '8726',
 '766376',
 '62546639',
 '94554267',
 '945537766',
 '32847',
 '32847',
 '667747',
 '26937',
 '74242737',
 '437626339',
 '26337766',
 '94554267',
 '769355',
 '7839278',
 '57',
 '425524437',
 '73966537',
 '762378766',
 '778488',
 '56739',
 '2255',
 '266723',
 '7467',
 '3472437',
 '7655273',
 '56637',
 '63937',
 '945766',
 '66673',
 '465336',
 '76246766',
 '625366236',
 '96864',
 '5464',
 '285467',
 '24747836736',
 '4855',
 '96864',
 '2366388',
 '369537',
 '57',
 '527766',
 '4295467',
 '3853',
 '763744839',
 '5646766',
 '42774766',
 '28242626',
 '5646766',
 '667769',
 '42774766',
 '44',
 '356737',
 '639866',
 '94483',
 '4255',
 '9285467',
 '44257',
 '648936',
 '24263537',
 '96864',
 '329',
 '328443789',
 '426736',
 '72636574',
 '48377376',
 '5377',
 '94554267',
 '26337766',
 '56637',
 '4633626',
 '57',
 '363766',
 '242839',
 '36967',
 '945766',
 '28753',
 '537837',
 '243779',
 '28664647',
 '2426',
 '94483',
 '46853',
 '28379',
 '6274',
 '4675467',
 '25363687',
 '9273',
 '2275766',
 '369',
 '92887',
 '648936',
 '32847',
 '437626339',
 '84667766',
 '463437',
 '769337',
 '22537',
 '645537',
 '26337766',
 '22672355',
 '276653',
 '7262439',
 '7467',
 '57',
 '269',
 '74455477',
 '56637',
 '98',
 '76887',
 '5646766',
 '7423',
 '4833626',
 '78663',
 '26337766',
 '66774766',
 '444',
 '42792',
 '2366388',
 '56637',
 '743723',
 '73739',
 '472426',
 '643353866',
 '367837',
 '2653626',
 '2825',
 '28779',
 '925537',
 '72684246',
 '2655467',
 '78663',
 '2253946',
 '4295467',
 '66673',
 '65766',
 '2789',
 '427242',
 '73937',
 '227237',
 '56637',
 '22672355',
 '5693',
 '932837',
 '667747',
 '9264',
 '648936',
 '7263377',
 '665462',
 '667747',
 '46692537',
 '4743346',
 '94554267',
 '57',
 '5664',
 '7262439',
 '7669',
 '37746692',
 '9663',
 '2866464426',
 '53664647',
 '48964',
 '62366253',
 '427747',
 '7839278',
 '5366339',
 '925866',
 '2366388',
 '2866464426',
 '778488',
 '227866',
 '32847',
 '6274',
 '22537',
 '5464',
 '62784639',
 '633462',
 '66639',
 '928766',
 '2655467',
 '44',
 '7429',
 '9664',
 '2876388',
 '427346',
 '27696',
 '945766',
 '2262246',
 '5463639',
 '526',
 '23267',
 '94554267',
 '35693',
 '687749',
 '3836837',
 '782739',
 '645537',
 '66673',
 '62269',
 '2246',
 '62774',
 '7264739',
 '7424273766',
 '73937',
 '94554267',
 '928766',
 '729937',
 '4868',
 '53947',
 '266637',
 '548',
 '4868',
 '564448',
 '769355',
 '94539',
 '96864',
 '463437',
 '94554267',
 '25827236',
 '73739',
 '3733626',
 '2973',
 '78554826',
 '76484',
 '3673',
 '65736',
 '7264739',
 '76484',
 '4729',
 '42937',
 '6225873',
 '762378766',
 '9653',
 '6266',
 '2789',
 '76484',
 '94554267',
 '4687866',
 '232537',
 '27696',
 '76246766',
 '76484',
 '442766',
 '57',
 '386226',
 '867737',
 '76484',
 '55463',
 '4295467',
 '227637',
 '6246639',
 '728837766',
 '2665',
 '763744839',
 '76484',
 '73837766',
 '764377',
 '7355377',
 '56277',
 '46227',
 '444',
 '835277839',
 '945766',
 '5646766',
 '356737',
 '367739',
 '64557',
 '5646766',
 '2624726',
 '44',
 '7467766',
 '788866',
 '763744839',
 '4273637',
 '4363749',
 '3836837',
 '94483',
 '2484773',
 '76484',
 '24264',
 '94483',
 '22774556',
 '4822273',
 '738377',
 '62784639',
 '343537',
 '343537',
 '266637',
 '2874377',
 '63666355',
 '687729',
 '48377376',
 '42645866',
 '93557',
 '74277',
 '4444467',
 '867737',
 '635766',
 '627436',
 '62227849',
 '5646766',
 '46639',
 '32847',
 '72423337',
 '427242',
 '3554688',
 '7467',
 '9273',
 '78688',
 '96864',
 '57',
 '73739',
 '76246766',
 '2355',
 '3429',
 '77288',
 '229837',
 '76484',
 '7262439',
 '232537',
 '2473',
 '32847',
 '3377355',
 '96864',
 '4444467',
 '648936',
 '22672355',
 '56739',
 '69377',
 '7435866',
 '437626339',
 '7849',
 '57',
 '5646766',
 '276657',
 '4868',
 '5646766',
 '94554267',
 '5264',
 '78554826',
 '34483762',
 '444',
 '92887',
 '42937',
 '56637',
 '7264739',
 '2655467',
 '69377',
 '78688',
 '7839278',
 '32847',
 '44',
 '5889',
 '4255',
 '367837',
 '96864',
 '32847',
 '62774',
 '2973',
 '4377372',
 '974448',
 '84667766',
 '66639',
 '76484',
 '373624',
 '887637',
 '57',
 '27696',
 '73739',
 '26936',
 '4255',
 '76653',
 '9285467',
 '227866',
 '4729',
 '7466667',
 '227736837',
 '3554688',
 '925537',
 '56637',
 '442766',
 '25275',
 '7264739',
 '57',
 '2366388',
 '72757',
 '57',
 '9233',
 '427747',
 '64557',
 '6363692',
 '93357',
 '47336',
 '73937',
 '427747',
 '6668692',
 '32847',
 '7262439',
 '2255',
 '367837',
 '65766',
 '3489437253',
 '3472437',
 '9264',
 '56739',
 '627436',
 '48674739',
 '9468377',
 '227837',
 '6835537',
 '26337766',
 '928766',
 '66726',
 '2277655',
 '635766',
 '42645866',
 '94483',
 '825339',
 '22537',
 '746453866',
 '76484',
 '7849',
 '772757',
 '38339',
 '887637',
 '276657',
 '227637',
 '76547',
 '2693',
 '764377',
 '94554267',
 '726435',
 '974448',
 '66639',
 '7264739',
 '266737',
 '57',
 '27696',
 '27696',
 '84667766',
 '945766',
 '28767',
 '72835',
 '7246438',
 '427747',
 '57',
 '272437',
 '94554267',
 '22537',
 '5664',
 '44257',
 '527736',
 '26337766',
 '5783437',
 '7655467',
 '769337',
 '25275',
 '86967363',
 '763744839',
 '26566',
 '62784639',
 '62784639',
 '2866464426',
 '366464839',
 '94554267',
 '8342',
 '4455',
 '945766',
 '484437',
 '6936',
 '78554826',
 '76626',
 '645537',
 '23779',
 '73739',
 '484437',
 '64557',
 '94554267',
 '22537',
 '635766',
 '522627',
 '5463639',
 '57',
 '76246766',
 '226666',
 '427242',
 '6252844546',
 '7838367',
 '32847',
 '4277355',
 '242839',
 '867737',
 '229837',
 '9455426766',
 '6668692',
 '645537',
 '3536464',
 '4833626',
 '56637',
 '726435',
 '2653626',
 '46873',
 '788866',
 '7849',
 '93557',
 '367739',
 '7423',
 '356737',
 '66673',
 '4255',
 '32847',
 '65766',
 '23267',
 '4377464',
 '242839',
 '62433',
 '57',
 '2484773',
 '427839',
 '94554267',
 '57',
 '62784639',
 '27696',
 '232537',
 '7424273766',
 '27696',
 '2874377',
 '62269',
 '9664',
 '7467766',
 '76484',
 '47336',
 '629',
 '426736',
 '66774766',
 '227837',
 '782739',
 '73966537',
 '633462',
 '46639',
 '4255',
 '47946',
 '66673',
 '426766',
 '366464839',
 '928377',
 '76484',
 '2825539',
 '94554267',
 '27263',
 '76484',
 '22552426',
 '57',
 '44',
 '4655263',
 '46692537',
 '76246766',
 '3392737',
 '8277839',
 '7262439',
 '76484',
 ...]

In [69]:
df = df.assign(phone_by_name=num_join_list)

In [70]:
df.head()

,customerid,name,address,citystatezip,birthdate,phone,phone_clean,last_name,phone_by_name
0,1001,Jack Quinn,201 E Park St,"Los Angeles, CA 91343",1960-05-14,805-287-8515,8052878515,"[, q, u, i, n, n, ]",78466
1,1002,David Powell,224C Tysens Ln,"Staten Island, NY 10306",1978-04-04,516-768-1652,5167681652,"[, p, o, w, e, l, l, ]",769355
2,1003,Carrie Green,1608 W 53rd Way,"Tampa, FL 33614",1969-01-21,727-209-0470,7272090470,"[, g, r, e, e, n, ]",47336
3,1004,Steven Miller,178½ E 7th St,"Manhattan, NY 10009",1953-08-17,607-941-9563,6079419563,"[, m, i, l, l, e, r, ]",645537
4,1005,Christine Powers,270 W 242nd St,"Bronx, NY 10463",1983-06-06,212-759-9043,2127599043,"[, p, o, w, e, r, s, ]",769377

In [71]:
detective_name = np.where(df.phone_clean.eq(df.phone_by_name))

In [72]:
detective_name

(array([2187]),)

In [73]:
df.iloc[2187]

customerid                                     3188
name                                 Sam Guttenberg
address                               221 Banker St
citystatezip                     Brooklyn, NY 11222
birthdate                                1998-05-30
phone                                  488-836-2374
phone_clean                              4888362374
last_name        [, g, u, t, t, e, n, b, e, r, g, ]
phone_by_name                            4888362374
Name: 2187, dtype: object

In [ ]:
df.phone_int = num_join_list

In [ ]:
df['phone_clean'] = df.phone_clean.astype(str)
df['phone_by_name'] = df.phone_by_name.astype(str)

In [ ]:
df.head()

In [ ]:
match = df.phone_clean.eq(df.phone_by_name)
match.nunique()

In [ ]:
match = df.phone_clean.eq(df.phone_by_name)
match.nunique()

In [ ]:
df.phone_clean.dtype

In [ ]:
detective_name

In [ ]:
z = df.num_int[0]
dd =  int(''.join(map(str, z)))

In [ ]:

s = ''.join(t)
s

In [ ]:
df.head()

In [ ]:
df_short_list = df.loc[df.name.str.len()==12]

In [ ]:
first_name = df_short_list.name[1]
first_name

In [ ]:
number_dictionary['abc']

In [ ]:
'd' in number_dictionary.keys()

In [ ]:
hey

In [ ]:
first_number = []
for letter in first_name:
    if letter in number_dictionary.keys():
        first_number.append(number_dictionary.values())

In [ ]:
short_list[0].

In [ ]:
num_lis = []
for name in df.name:
    name.split()

In [ ]:
df['phone_to_text'] =

In [ ]:
if df.name in number_dictionary:
    print(ok)

In [ ]:
len(df['phone'][0])

In [ ]:
df['name'].head()

In [ ]:
df['name'].max()

In [ ]:
df.name.str.len().max()

In [ ]:
short_list = df.loc[df.name.str.len()==12]

In [ ]:
df.iloc[1031]

In [ ]:
np.where(df.name.str.len().max() == 30,df['name'])